### PR TITLE
Fix unit test for ptable plotly

### PR DESCRIPTION
**Pull request by DanielYang59**
For some reason I noticed these tests failed both locally and in CI (and therefore open this PR wanted to fix them), but now they all pass?

### CODE REVIEW

**Comment by DanielYang59** [comment]
Also notice one unit test failed in CI but passed locally https://github.com/janosh/pymatviz/pull/157#issuecomment-2217076486

**Comment by janosh** [comment]
thanks for checking! weird that they pass now. they were failing in CI just a few days ago. still don't know why. happy to merge this if you want to undraft

**Comment by DanielYang59** [comment]
Yes it once failed locally on my machine too. Not sure what the reason. I would undraft this for now until the issue pop up again (hopefully not)

**Review by janosh — APPROVED** [review]
thanks @DanielYang59! 👍

**Comment by DanielYang59** [comment]
No problem :)

**Pull request merged**
