### PR TITLE
Python 3.7 support

### PR DESCRIPTION
**Pull request by janosh**
Following https://github.com/janosh/pymatviz/issues/17#issuecomment-1272230416.

### CODE REVIEW

**Comment by janosh** [comment]
@sgbaird Could you take [v0.5.1](https://github.com/janosh/pymatviz/releases/tag/v0.5.1) for a spin on Colab and let me know if you encounter errors?

**Comment by sgbaird** [comment]
Will do!

**Comment by sgbaird** [comment]
@janosh, I gave it a try, and seems to be working fine! Thank you!

**Comment by janosh** [comment]
Nice, glad to hear it. 😄

**Pull request merged**
