### PR TITLE
pin kaleido==0.2.1

### PR DESCRIPTION
**Pull request by theochemtheo**
* Pins `kaleido==0.2.1`, closing #216

### CODE REVIEW

**Review by janosh — APPROVED** [review]
@theochemtheo thanks for reporting and fixing! 👍

**Comment by DanielYang59** [comment]
Should that pin be [`0.2.1.post1`](https://github.com/plotly/Kaleido/releases) instead of `0.2.1post1`?

For some reason I didn't see `kaleido==0.2.1.post1` in my available versions from `pip` for some reason (I'm also working on MacOS)?
```
>>> pip index versions kaleido
kaleido (0.2.1)
Available versions: 0.2.1, 0.2.0
```

**Comment by janosh** [comment]
[yes, good catch](https://pypi.org/project/kaleido/0.2.1.post1/)

**Comment by DanielYang59** [comment]
Can you install `pip install kaleido==0.2.1.post1` (with dot before `post1`)? I cannot install it either:
```
pip install kaleido==0.2.1.post1
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement kaleido==0.2.1.post1 (from versions: 0.2.0rc1, 0.2.0, 0.2.1)
ERROR: No matching distribution found for kaleido==0.2.1.post1
```

**Comment by janosh** [comment]
get the same error but that's consistent with there being [only a linux wheel](https://pypi.org/project/kaleido/0.2.1.post1/#files)

**Comment by DanielYang59** [comment]
Yes there's only a wheel for ARM32 Linux (I don't think pip would automatically pick this version) so I was wondering why the original author would have that issue (apple silicon is ARM64).

**Pull request merged**
